
# Function for getting the most freqwuent word from a text with only the k (pattern length) known, and return a list of frequent k-mer word.
def GetFreqWord(text, k):
    Map = {}
    for i in range(len(text)-k):
        word = text[i:i+k]
        if word in Map:
            Map[word]+=1
        else:
            Map[word]=1
    maxVal = max(Map.values())
    res = [kmer for kmer,freq in Map.items() if freq==maxVal]
    return res

text = 'TCAGAGACTAACATCAACATCAGAGACTGTAGACTTGATCAGAGACTGTGTAAAGCCTGAAGAAATGTGTAAAGCCTGAAGAAATGTGTAAAGCCTGAAGAAATAACATCAACAAACATCAACAAACATCAACAGTGTAAAGCCGTAGACTTGAGTAGACTTGAAACATCAACAGTGTAAAGCCTGAAGAAATTCAGAGACTTGAAGAAATGTGTAAAGCCGTAGACTTGAAACATCAACAAACATCAACATCAGAGACTTCAGAGACTTCAGAGACTAACATCAACATGAAGAAATTGAAGAAATTCAGAGACTGTGTAAAGCCAACATCAACATGAAGAAATGTGTAAAGCCTGAAGAAATGTAGACTTGAGTAGACTTGATGAAGAAATTCAGAGACTAACATCAACAGTAGACTTGAGTGTAAAGCCGTGTAAAGCCTCAGAGACTAACATCAACAGTAGACTTGATCAGAGACTGTGTAAAGCCGTGTAAAGCCGTGTAAAGCCGTGTAAAGCCTGAAGAAATGTGTAAAGCCAACATCAACAGTGTAAAGCCTCAGAGACTAACATCAACAAACATCAACAGTGTAAAGCCTCAGAGACTGTAGACTTGATCAGAGACTGTAGACTTGATGAAGAAATGTGTAAAGCCGTGTAAAGCCTCAGAGACTGTGTAAAGCCGTAGACTTGATGAAGAAATGTAGACTTGATGAAGAAATAACATCAACATCAGAGACTGTAGACTTGAAACATCAACAAACATCAACAAACATCAACATGAAGAAATGTAGACTTGAAACATCAACAGTAGACTTGATGAAGAAATAACATCAACATCAGAGACTTGAAGAAATAACATCAACATCAGAGACTTCAGAGACTTCAGAGACTTCAGAGACTGTGTAAAGCCTGAAGAAATGTAGACTTGATCAGAGACTTGAAGAAATTCAGAGACTTCAGAGACT'
ResFreq = []
ResFreq = GetFreqWord(text,11)
print(ResFreq)