# Given the text and the pattern, calculate how many times the pattern occur on the text.

Text = 'CAACGGCCAACGGCCAGCAACGGCCAACGGCCAGCAACGGCGACTCAGGTTGAATAGATCAACGGCCAACGGCCAACCAGCAACGGCTGCGCCAACGGCGGCAACGGCCCTATCAACGGCGTGCTCCAACGGCGCAACGGCCACAACGGCTAATCAACGGCGCACTCAACGGCCAACGGCAACCAACGGCTTGGCAACGGCACAACGGCATCAACGGCAGAAGCAACGGCGACAACGGCCAACGGCCAACGGCTCAACGGCCAACGGCGTACAACGGCCAACGGCTCCAACGGCCGTGATACAACGGCCAACGGCGCAACGGCCAACGGCCCACTTTACAACGGCTCCAACGGCTCCAACGGCCAACGGCGCAACGGCATTCAACGGCGCAACGGCGATGCAACGGCCAACGGCACCAACGGCCAACGGCCAACGGCCCAACGGCCAACGGCCAACGGCCCAACGGCGGCAACGGCCAACGGCTGTCAACGGCCAACGGCCAACGGCCAACGGCCGGATCAACGGCGGTGCAACGGCGGACCAACGGCCAACGGCTAACCAACGGCCGCCCTCCATCAACGGCGCCAACGGCTCAACGGCTCATTCAACGGCCACAACGGCATCAACGGCGGATAAGTCCAACGCACTTTCCAACGGCGAACAACGGCGCAACGGCCCTTCAACGGCACCAACGGCCAACGGCTTTTGCAACGGCTTCAACGGCGCAACGGCGGCGCGAATCAACGGCTCGCAAACCAACGGCCAACGGCGTGACTTAACCAACGGCAGCAACGGCCAACGGCCGGCAACGGCAAGTCAACGGCCAACGGCTCAACGGCATCCAACGGCTTCAACGGCCAACGGCTACCCCAACGGCTCAACGGCGCAACGGCCCAACGGCTATCCTCAACGGCCAACGGCATCTCAACGGCCGTGTAATCAACGGCCAACGGCGGGACAACGGCCAACGGCATCAACGGCACAACAACGGCTCCAACGGCCAACGGCCGATCGAACAACAACGGCATCTCCAACGGC'
pattern = 'CAACGGCCA'

#for i in range(len(Text) - len(pattern)):

#print(len(Text)) = 1045
#len(pattern) = 9
Count = 0
for i in range(len(Text) - len(pattern)):
    if Text[i:i+len(pattern)] == pattern:
        Count+=1
        #print('Found same')
print(Count)

